### ISSUE TITLE
Fails to load local path in packaged builds

### ISSUE THREAD

**Issue by nistic** [ufna/VaQuoleUI#12]
Loading local paths using "vaquole://stuff/example.html" works in the editor but does not work in packaged builds (pak or non-pak versions)

**Comment by ufna** [comment]
Because files from _stuff_ folder are not imported as "ue4 content", you should put this folder into packaged build manually. It's not a bug at all, because library works outside the UE4 and should have direct access to files.

I'll make make tests tomorrow, but I think that right place will be packaged _YourProject_ root folder.

**Comment by ufna** [comment]
Somewhy in packaged game **FPaths::GameDir();** returns relative path instead of absolute. I'll take a look how to fix it.

**Comment by nistic** [comment]
You're the man!

**Comment by nistic** [comment]
Changing that line to:

**FString GameDir = FPaths::ConvertRelativePathToFull(FPaths::GameDir());**

Fixed it for me on a 4.2 packaged project with the "Shipping" configuration (non-pak) and it works in the editor. I'll test some other configurations and get back to you.

**Comment by nistic** [comment]
Works on a 4.2 packaged project with the "Development" configuration (pak version) too, looks like that worked :)

**Comment by ufna** [comment]
Thanks @nistic , I've commited the fix into develop branch :)
